import {
  collectActions,
  collectStatePaths,
  collectUsedComponents,
  serializeProps,
  traverseSpec,
  type GeneratedFile,
} from '@json-render/codegen';
import type { Spec } from '@json-render/core';
import type { DesignSpec } from '@next-dev/editor-core';
import { buildAppFile, buildCssFile, SUPPORTED_COMPONENT_CASES } from './code-export-ui.js';

export interface ExportCodeOptions {
  projectName?: string;
}

export interface GeneratedCodeProject {
  framework: 'react-vite';
  displayName: string;
  packageName: string;
  entryFile: string;
  componentTypes: string[];
  unsupportedComponents: string[];
  statePaths: string[];
  actions: string[];
  files: GeneratedFile[];
}

type ExportableElement = Spec['elements'][string] & {
  __editor?: {
    hidden?: boolean;
  };
};

const FALLBACK_PROJECT_NAME = 'designforge-export';

function cloneJson<T>(value: T): T {
  return JSON.parse(JSON.stringify(value)) as T;
}

function compactProps(props: Record<string, unknown>): Record<string, unknown> {
  return Object.fromEntries(
    Object.entries(props).filter(([, value]) => value !== undefined && value !== null),
  );
}

function sanitizeSpecForExport(spec: DesignSpec): Spec {
  const elements: Spec['elements'] = {};

  const visit = (elementId: string): string | null => {
    const rawElement = spec.elements[elementId] as ExportableElement | undefined;
    if (!rawElement || rawElement.__editor?.hidden) {
      return null;
    }

    const cleanChildren = (rawElement.children ?? [])
      .map((childId) => visit(childId))
      .filter((childId): childId is string => childId !== null);

    const cleanElement = cloneJson(rawElement) as unknown as Record<string, unknown>;
    delete cleanElement.__editor;
    cleanElement.children = cleanChildren;
    cleanElement.props = compactProps((cleanElement.props as Record<string, unknown> | undefined) ?? {});
    elements[elementId] = cleanElement as unknown as Spec['elements'][string];

    return elementId;
  };

  const rootId = visit(spec.root);
  if (!rootId) {
    throw new Error('Cannot export a design with a hidden or missing root element.');
  }

  return {
    root: rootId,
    elements,
    state: cloneJson(spec.state ?? {}),
  };
}

function slugifyProjectName(projectName: string): string {
  const slug = projectName
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');

  return slug || FALLBACK_PROJECT_NAME;
}

function toDisplayName(projectName: string): string {
  return projectName
    .trim()
    .replace(/[-_]+/g, ' ')
    .replace(/\s+/g, ' ')
    .split(' ')
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ') || 'DesignForge Export';
}

function buildTreeSummary(spec: Spec): string {
  const lines: string[] = [];
  traverseSpec(spec, (element, key, depth) => {
    lines.push(`${'  '.repeat(depth)}- ${key}: ${element.type}`);
  });
  return lines.join('\n');
}

function buildDesignSpecFile(spec: Spec): string {
  return `export interface ExportedElement {
  type: string;
  props: Record<string, unknown>;
  children?: string[];
}

export interface ExportedDesignSpec {
  root: string;
  elements: Record<string, ExportedElement>;
  state: Record<string, unknown>;
}

export const designSpec: ExportedDesignSpec = ${JSON.stringify(spec, null, 2)};
`;
}

function buildReadme(args: {
  displayName: string;
  nodeCount: number;
  rootType: string;
  componentTypes: string[];
  unsupportedComponents: string[];
  statePaths: string[];
  actions: string[];
  treeSummary: string;
  rootPreview: string;
}): string {
  const stateSection = args.statePaths.length > 0
    ? args.statePaths.map((path) => `- \`${path}\``).join('\n')
    : '- None detected';
  const actionSection = args.actions.length > 0
    ? args.actions.map((action) => `- \`${action}\``).join('\n')
    : '- None detected';
  const unsupportedSection = args.unsupportedComponents.length > 0
    ? `\n## Unsupported Components\n\nThese components do not have a dedicated renderer in this export yet and will show as placeholders:\n\n${args.unsupportedComponents.map((component) => `- \`${component}\``).join('\n')}\n`
    : '';

  return `# ${args.displayName}

Generated by DesignForge as a standalone React + Vite project.

## Run It

\`\`\`bash
pnpm install
pnpm dev
\`\`\`

## Design Summary

- Root component: \`${args.rootType}\`
- Exported nodes: ${args.nodeCount}
- Used components: ${args.componentTypes.map((component) => `\`${component}\``).join(', ')}
- Root JSX preview: \`${args.rootPreview}\`

## State Paths

${stateSection}

## Actions

${actionSection}

## Notes

- The current layout is exported as standalone React code with no DesignForge runtime dependency.
- Initial design state is preserved in [src/design-spec.ts](./src/design-spec.ts).
- If you add interactive state bindings or action handlers later, wire them manually inside [src/App.tsx](./src/App.tsx).
${unsupportedSection}
## Tree

\`\`\`text
${args.treeSummary}
\`\`\`
`;
}

function buildPackageJson(packageName: string): string {
  return JSON.stringify({
    name: packageName,
    private: true,
    version: '0.0.0',
    type: 'module',
    scripts: {
      dev: 'vite',
      build: 'tsc && vite build',
      preview: 'vite preview',
    },
    dependencies: {
      react: '^19.2.0',
      'react-dom': '^19.2.0',
    },
    devDependencies: {
      '@types/react': '^19.2.2',
      '@types/react-dom': '^19.2.2',
      '@vitejs/plugin-react': '^4.7.0',
      typescript: '^5.9.2',
      vite: '^7.3.1',
    },
  }, null, 2);
}

function buildTsconfig(): string {
  return JSON.stringify({
    compilerOptions: {
      target: 'ES2022',
      useDefineForClassFields: true,
      lib: ['DOM', 'DOM.Iterable', 'ES2022'],
      allowJs: false,
      skipLibCheck: true,
      esModuleInterop: true,
      allowSyntheticDefaultImports: true,
      strict: true,
      forceConsistentCasingInFileNames: true,
      module: 'ESNext',
      moduleResolution: 'Bundler',
      resolveJsonModule: true,
      isolatedModules: true,
      noEmit: true,
      jsx: 'react-jsx',
    },
    include: ['src'],
  }, null, 2);
}

function buildViteConfig(): string {
  return `import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
});
`;
}

function buildIndexHtml(displayName: string): string {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${displayName}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`;
}

function buildMainTsx(): string {
  return `import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import App from './App';
import './index.css';

const root = document.getElementById('root');

if (!root) {
  throw new Error('Root element not found.');
}

createRoot(root).render(
  <StrictMode>
    <App />
  </StrictMode>,
);
`;
}

function buildGitIgnore(): string {
  return `node_modules
dist
`;
}

export function generateReactViteProject(
  spec: DesignSpec,
  options: ExportCodeOptions = {},
): GeneratedCodeProject {
  const exportSpec = sanitizeSpecForExport(spec);
  const packageName = slugifyProjectName(options.projectName ?? FALLBACK_PROJECT_NAME);
  const displayName = toDisplayName(options.projectName ?? packageName);
  const componentTypes = Array.from(collectUsedComponents(exportSpec)).sort();
  const unsupportedComponents = componentTypes.filter((componentType) => !SUPPORTED_COMPONENT_CASES[componentType]);
  const statePaths = Array.from(collectStatePaths(exportSpec)).sort();
  const actions = Array.from(collectActions(exportSpec)).sort();
  const treeSummary = buildTreeSummary(exportSpec);
  const rootElement = exportSpec.elements[exportSpec.root];
  const rootPropsPreview = serializeProps(compactProps(rootElement?.props ?? {}), {
    quotes: 'double',
    indent: 2,
  });
  const rootPreview = rootElement
    ? `<${rootElement.type}${rootPropsPreview ? ` ${rootPropsPreview}` : ''}>...</${rootElement.type}>`
    : '<Unknown />';

  const files: GeneratedFile[] = [
    { path: 'package.json', content: buildPackageJson(packageName) },
    { path: 'tsconfig.json', content: buildTsconfig() },
    { path: 'vite.config.ts', content: buildViteConfig() },
    { path: 'index.html', content: buildIndexHtml(displayName) },
    { path: '.gitignore', content: buildGitIgnore() },
    { path: 'src/main.tsx', content: buildMainTsx() },
    { path: 'src/index.css', content: buildCssFile() },
    { path: 'src/design-spec.ts', content: buildDesignSpecFile(exportSpec) },
    { path: 'src/App.tsx', content: buildAppFile(componentTypes) },
    {
      path: 'README.md',
      content: buildReadme({
        displayName,
        nodeCount: Object.keys(exportSpec.elements).length,
        rootType: rootElement?.type ?? 'Unknown',
        componentTypes,
        unsupportedComponents,
        statePaths,
        actions,
        treeSummary,
        rootPreview,
      }),
    },
  ];

  return {
    framework: 'react-vite',
    displayName,
    packageName,
    entryFile: 'src/App.tsx',
    componentTypes,
    unsupportedComponents,
    statePaths,
    actions,
    files,
  };
}
