export enum ProFieldValueType {
  Text = 'text',
  Password = 'password',
  Money = 'money',
  Index = 'index',
  IndexBorder = 'indexBorder',
  Option = 'option',
  Textarea = 'textarea',
  Date = 'date',
  DateWeek = 'dateWeek',
  DateMonth = 'dateMonth',
  DateQuarter = 'dateQuarter',
  DateYear = 'dateYear',
  DateTime = 'dateTime',
  FromNow = 'fromNow',
  DateRange = 'dateRange',
  DateTimeRange = 'dateTimeRange',
  DateWeekRange = 'dateWeekRange',
  DateMonthRange = 'dateMonthRange',
  DateQuarterRange = 'dateQuarterRange',
  DateYearRange = 'dateYearRange',
  Time = 'time',
  TimeRange = 'timeRange',
  Select = 'select',
  Checkbox = 'checkbox',
  Rate = 'rate',
  Slider = 'slider',
  Radio = 'radio',
  RadioButton = 'radioButton',
  Progress = 'progress',
  Percent = 'percent',
  Digit = 'digit',
  DigitRange = 'digitRange',
  Second = 'second',
  Code = 'code',
  JsonCode = 'jsonCode',
  Avatar = 'avatar',
  Switch = 'switch',
  Image = 'image',
  Cascader = 'cascader',
  TreeSelect = 'treeSelect',
  Color = 'color',
  Segmented = 'segmented',
  Group = 'group',
  FormList = 'formList',
  FormSet = 'formSet',
  Divider = 'divider',
  Dependency = 'dependency',
}

export const valueTypeArray = [
  'text',
  'password',
  'money',
  'textarea',
  'option',
  'date',
  'dateWeek',
  'dateMonth',
  'dateQuarter',
  'dateYear',
  'dateRange',
  'dateTimeRange',
  'dateTime',
  'time',
  'timeRange',
  'text',
  'select',
  'checkbox',
  'rate',
  'radio',
  'radioButton',
  'index',
  'indexBorder',
  'progress',
  'percent',
  'digit',
  'second',
  'avatar',
  'code',
  'switch',
  'fromNow',
  'image',
  'jsonCode',
  'formList',
]
