// ─── Core Types ─────────────────────────────────────────────

export type Scope = 'global' | 'workspace';

/** A skill parsed from .agents/skills/<name>/SKILL.md */
export interface Skill {
  name: string;
  description: string;
  content: string;
  filePath: string;
}

/** A workflow parsed from .agents/workflows/<name>.md */
export interface Workflow {
  name: string;
  description: string;
  content: string;
  filePath: string;
}

/** MCP server definition from .agents/mcp.json */
export interface McpServer {
  type?: string;
  command?: string;
  args?: string[];
  url?: string;
  headers?: Record<string, string>;
  env?: Record<string, string>;
  [key: string]: unknown;
}

/** Everything scanned from .agents/ */
export interface AgentsConfig {
  /** Content from AGENTS.md — project-wide agent instructions */
  agentsmd: string | null;
  /** Content from SKILLS.md — skills index */
  skillsmd: string | null;
  skills: Skill[];
  workflows: Workflow[];
  /** MCP servers from mcp.json */
  mcpServers: Record<string, McpServer>;
}

/** A file generated by a target adapter */
export interface GeneratedFile {
  relativePath: string;
  content: string;
  source: string;
}

// ─── Target Registry ────────────────────────────────────────

export type TargetName =
  | 'cursor'
  | 'copilot'
  | 'windsurf'
  | 'gemini'
  | 'claude';

export interface TargetDefinition {
  name: TargetName;
  label: string;
  implemented: boolean;
  supportedScopes: Scope[];
  defaultScope: Scope;

  /** Paths to check if the tool is installed (global & workspace) */
  detectPaths: (home: string, cwd: string) => string[];

  /** Resolve the output root for a given scope */
  resolveOutputRoot: (home: string, cwd: string, scope: Scope) => string;

  /** Gitignore entries for this target (workspace scope only) */
  gitignoreEntries: string[];

  /** Generate files from .agents config */
  generate: (config: AgentsConfig, scope: Scope) => GeneratedFile[];
}

export interface DetectedTool {
  name: TargetName;
  label: string;
  detected: boolean;
  reason: string;
}

// ─── RC Config ──────────────────────────────────────────────

/** Project-level .agentrc configuration */
export interface AgentRc {
  /** Which targets to sync (default: auto-detect all) */
  targets?: TargetName[];
  /** Default scope for sync (default: workspace) */
  scope?: Scope;
  /** Auto-manage .gitignore (default: true) */
  gitignore?: boolean;
  /** Sync MCP servers (default: true) */
  mcp?: boolean;
  /** Root files to generate (default: ['AGENTS.md', 'SKILLS.md']) */
  rootFiles?: string[];
}
