/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * Swagger Petstore
 * This is a sample server Petstore server.  You can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).  For this sample, you can use the api key `special-key` to test the authorization filters.
 * OpenAPI spec version: 1.0.7
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  LoginUserParams,
  User,
  UserArrayBody
} from '../swaggerPetstore.schemas';

import { customRequest } from '../../mutator/umi-request';
import type { ErrorType , BodyType } from '../../mutator/umi-request';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



/**
 * @summary Get user by user name
 */
export type getUserByNameResponse200 = {
  data: User
  status: 200
}

export type getUserByNameResponse400 = {
  data: void
  status: 400
}

export type getUserByNameResponse404 = {
  data: void
  status: 404
}
    
export type getUserByNameResponseSuccess = (getUserByNameResponse200) & {
  headers: Headers;
};
export type getUserByNameResponseError = (getUserByNameResponse400 | getUserByNameResponse404) & {
  headers: Headers;
};

export type getUserByNameResponse = (getUserByNameResponseSuccess | getUserByNameResponseError)

export const getGetUserByNameUrl = (username: string,) => {


  

  return `https://petstore.swagger.io/v2/user/${username}`
}

export const getUserByName = async (username: string, options?: RequestInit): Promise<getUserByNameResponse> => {
  
  return customRequest<getUserByNameResponse>(getGetUserByNameUrl(username),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetUserByNameQueryKey = (username?: string,) => {
    return [
    `https://petstore.swagger.io/v2/user/${username}`
    ] as const;
    }

    
export const getGetUserByNameQueryOptions = <TData = Awaited<ReturnType<typeof getUserByName>>, TError = ErrorType<void>>(username: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserByName>>, TError, TData>>, request?: SecondParameter<typeof customRequest>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUserByNameQueryKey(username);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserByName>>> = ({ signal }) => getUserByName(username, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(username), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUserByName>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUserByNameQueryResult = NonNullable<Awaited<ReturnType<typeof getUserByName>>>
export type GetUserByNameQueryError = ErrorType<void>


export function useGetUserByName<TData = Awaited<ReturnType<typeof getUserByName>>, TError = ErrorType<void>>(
 username: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserByName>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserByName>>,
          TError,
          Awaited<ReturnType<typeof getUserByName>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customRequest>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserByName<TData = Awaited<ReturnType<typeof getUserByName>>, TError = ErrorType<void>>(
 username: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserByName>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserByName>>,
          TError,
          Awaited<ReturnType<typeof getUserByName>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customRequest>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUserByName<TData = Awaited<ReturnType<typeof getUserByName>>, TError = ErrorType<void>>(
 username: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserByName>>, TError, TData>>, request?: SecondParameter<typeof customRequest>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get user by user name
 */

export function useGetUserByName<TData = Awaited<ReturnType<typeof getUserByName>>, TError = ErrorType<void>>(
 username: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserByName>>, TError, TData>>, request?: SecondParameter<typeof customRequest>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUserByNameQueryOptions(username,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * This can only be done by the logged in user.
 * @summary Updated user
 */
export type updateUserResponse400 = {
  data: void
  status: 400
}

export type updateUserResponse404 = {
  data: void
  status: 404
}
    
;
export type updateUserResponseError = (updateUserResponse400 | updateUserResponse404) & {
  headers: Headers;
};

export type updateUserResponse = (updateUserResponseError)

export const getUpdateUserUrl = (username: string,) => {


  

  return `https://petstore.swagger.io/v2/user/${username}`
}

export const updateUser = async (username: string,
    user: User, options?: RequestInit): Promise<updateUserResponse> => {
  
  return customRequest<updateUserResponse>(getUpdateUserUrl(username),
  {      
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      user,)
  }
);}




export const getUpdateUserMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUser>>, TError,{username: string;data: BodyType<User>}, TContext>, request?: SecondParameter<typeof customRequest>}
): UseMutationOptions<Awaited<ReturnType<typeof updateUser>>, TError,{username: string;data: BodyType<User>}, TContext> => {

const mutationKey = ['updateUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateUser>>, {username: string;data: BodyType<User>}> = (props) => {
          const {username,data} = props ?? {};

          return  updateUser(username,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateUserMutationResult = NonNullable<Awaited<ReturnType<typeof updateUser>>>
    export type UpdateUserMutationBody = BodyType<User>
    export type UpdateUserMutationError = ErrorType<void>

    /**
 * @summary Updated user
 */
export const useUpdateUser = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateUser>>, TError,{username: string;data: BodyType<User>}, TContext>, request?: SecondParameter<typeof customRequest>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateUser>>,
        TError,
        {username: string;data: BodyType<User>},
        TContext
      > => {

      const mutationOptions = getUpdateUserMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * This can only be done by the logged in user.
 * @summary Delete user
 */
export type deleteUserResponse400 = {
  data: void
  status: 400
}

export type deleteUserResponse404 = {
  data: void
  status: 404
}
    
;
export type deleteUserResponseError = (deleteUserResponse400 | deleteUserResponse404) & {
  headers: Headers;
};

export type deleteUserResponse = (deleteUserResponseError)

export const getDeleteUserUrl = (username: string,) => {


  

  return `https://petstore.swagger.io/v2/user/${username}`
}

export const deleteUser = async (username: string, options?: RequestInit): Promise<deleteUserResponse> => {
  
  return customRequest<deleteUserResponse>(getDeleteUserUrl(username),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteUserMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError,{username: string}, TContext>, request?: SecondParameter<typeof customRequest>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError,{username: string}, TContext> => {

const mutationKey = ['deleteUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteUser>>, {username: string}> = (props) => {
          const {username} = props ?? {};

          return  deleteUser(username,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteUserMutationResult = NonNullable<Awaited<ReturnType<typeof deleteUser>>>
    
    export type DeleteUserMutationError = ErrorType<void>

    /**
 * @summary Delete user
 */
export const useDeleteUser = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteUser>>, TError,{username: string}, TContext>, request?: SecondParameter<typeof customRequest>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteUser>>,
        TError,
        {username: string},
        TContext
      > => {

      const mutationOptions = getDeleteUserMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * This can only be done by the logged in user.
 * @summary Create user
 */
export type createUserResponseDefault = {
  data: void
  status: number
}
    
;
export type createUserResponseError = (createUserResponseDefault) & {
  headers: Headers;
};

export type createUserResponse = (createUserResponseError)

export const getCreateUserUrl = () => {


  

  return `https://petstore.swagger.io/v2/user`
}

export const createUser = async (user: User, options?: RequestInit): Promise<createUserResponse> => {
  
  return customRequest<createUserResponse>(getCreateUserUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      user,)
  }
);}




export const getCreateUserMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUser>>, TError,{data: BodyType<User>}, TContext>, request?: SecondParameter<typeof customRequest>}
): UseMutationOptions<Awaited<ReturnType<typeof createUser>>, TError,{data: BodyType<User>}, TContext> => {

const mutationKey = ['createUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createUser>>, {data: BodyType<User>}> = (props) => {
          const {data} = props ?? {};

          return  createUser(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateUserMutationResult = NonNullable<Awaited<ReturnType<typeof createUser>>>
    export type CreateUserMutationBody = BodyType<User>
    export type CreateUserMutationError = ErrorType<void>

    /**
 * @summary Create user
 */
export const useCreateUser = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUser>>, TError,{data: BodyType<User>}, TContext>, request?: SecondParameter<typeof customRequest>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createUser>>,
        TError,
        {data: BodyType<User>},
        TContext
      > => {

      const mutationOptions = getCreateUserMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Creates list of users with given input array
 */
export type createUsersWithArrayInputResponseDefault = {
  data: void
  status: number
}
    
;
export type createUsersWithArrayInputResponseError = (createUsersWithArrayInputResponseDefault) & {
  headers: Headers;
};

export type createUsersWithArrayInputResponse = (createUsersWithArrayInputResponseError)

export const getCreateUsersWithArrayInputUrl = () => {


  

  return `https://petstore.swagger.io/v2/user/createWithArray`
}

export const createUsersWithArrayInput = async (userArrayBody: UserArrayBody, options?: RequestInit): Promise<createUsersWithArrayInputResponse> => {
  
  return customRequest<createUsersWithArrayInputResponse>(getCreateUsersWithArrayInputUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      userArrayBody,)
  }
);}




export const getCreateUsersWithArrayInputMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUsersWithArrayInput>>, TError,{data: BodyType<UserArrayBody>}, TContext>, request?: SecondParameter<typeof customRequest>}
): UseMutationOptions<Awaited<ReturnType<typeof createUsersWithArrayInput>>, TError,{data: BodyType<UserArrayBody>}, TContext> => {

const mutationKey = ['createUsersWithArrayInput'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createUsersWithArrayInput>>, {data: BodyType<UserArrayBody>}> = (props) => {
          const {data} = props ?? {};

          return  createUsersWithArrayInput(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateUsersWithArrayInputMutationResult = NonNullable<Awaited<ReturnType<typeof createUsersWithArrayInput>>>
    export type CreateUsersWithArrayInputMutationBody = BodyType<UserArrayBody>
    export type CreateUsersWithArrayInputMutationError = ErrorType<void>

    /**
 * @summary Creates list of users with given input array
 */
export const useCreateUsersWithArrayInput = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUsersWithArrayInput>>, TError,{data: BodyType<UserArrayBody>}, TContext>, request?: SecondParameter<typeof customRequest>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createUsersWithArrayInput>>,
        TError,
        {data: BodyType<UserArrayBody>},
        TContext
      > => {

      const mutationOptions = getCreateUsersWithArrayInputMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Creates list of users with given input array
 */
export type createUsersWithListInputResponseDefault = {
  data: void
  status: number
}
    
;
export type createUsersWithListInputResponseError = (createUsersWithListInputResponseDefault) & {
  headers: Headers;
};

export type createUsersWithListInputResponse = (createUsersWithListInputResponseError)

export const getCreateUsersWithListInputUrl = () => {


  

  return `https://petstore.swagger.io/v2/user/createWithList`
}

export const createUsersWithListInput = async (userArrayBody: UserArrayBody, options?: RequestInit): Promise<createUsersWithListInputResponse> => {
  
  return customRequest<createUsersWithListInputResponse>(getCreateUsersWithListInputUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      userArrayBody,)
  }
);}




export const getCreateUsersWithListInputMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUsersWithListInput>>, TError,{data: BodyType<UserArrayBody>}, TContext>, request?: SecondParameter<typeof customRequest>}
): UseMutationOptions<Awaited<ReturnType<typeof createUsersWithListInput>>, TError,{data: BodyType<UserArrayBody>}, TContext> => {

const mutationKey = ['createUsersWithListInput'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createUsersWithListInput>>, {data: BodyType<UserArrayBody>}> = (props) => {
          const {data} = props ?? {};

          return  createUsersWithListInput(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateUsersWithListInputMutationResult = NonNullable<Awaited<ReturnType<typeof createUsersWithListInput>>>
    export type CreateUsersWithListInputMutationBody = BodyType<UserArrayBody>
    export type CreateUsersWithListInputMutationError = ErrorType<void>

    /**
 * @summary Creates list of users with given input array
 */
export const useCreateUsersWithListInput = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createUsersWithListInput>>, TError,{data: BodyType<UserArrayBody>}, TContext>, request?: SecondParameter<typeof customRequest>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createUsersWithListInput>>,
        TError,
        {data: BodyType<UserArrayBody>},
        TContext
      > => {

      const mutationOptions = getCreateUsersWithListInputMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * @summary Logs user into the system
 */
export type loginUserResponse200 = {
  data: string
  status: 200
}

export type loginUserResponse400 = {
  data: void
  status: 400
}
    
export type loginUserResponseSuccess = (loginUserResponse200) & {
  headers: Headers;
};
export type loginUserResponseError = (loginUserResponse400) & {
  headers: Headers;
};

export type loginUserResponse = (loginUserResponseSuccess | loginUserResponseError)

export const getLoginUserUrl = (params: LoginUserParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://petstore.swagger.io/v2/user/login?${stringifiedParams}` : `https://petstore.swagger.io/v2/user/login`
}

export const loginUser = async (params: LoginUserParams, options?: RequestInit): Promise<loginUserResponse> => {
  
  return customRequest<loginUserResponse>(getLoginUserUrl(params),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getLoginUserQueryKey = (params?: LoginUserParams,) => {
    return [
    `https://petstore.swagger.io/v2/user/login`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getLoginUserQueryOptions = <TData = Awaited<ReturnType<typeof loginUser>>, TError = ErrorType<void>>(params: LoginUserParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof loginUser>>, TError, TData>>, request?: SecondParameter<typeof customRequest>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLoginUserQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof loginUser>>> = ({ signal }) => loginUser(params, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof loginUser>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type LoginUserQueryResult = NonNullable<Awaited<ReturnType<typeof loginUser>>>
export type LoginUserQueryError = ErrorType<void>


export function useLoginUser<TData = Awaited<ReturnType<typeof loginUser>>, TError = ErrorType<void>>(
 params: LoginUserParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof loginUser>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof loginUser>>,
          TError,
          Awaited<ReturnType<typeof loginUser>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customRequest>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLoginUser<TData = Awaited<ReturnType<typeof loginUser>>, TError = ErrorType<void>>(
 params: LoginUserParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof loginUser>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof loginUser>>,
          TError,
          Awaited<ReturnType<typeof loginUser>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customRequest>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLoginUser<TData = Awaited<ReturnType<typeof loginUser>>, TError = ErrorType<void>>(
 params: LoginUserParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof loginUser>>, TError, TData>>, request?: SecondParameter<typeof customRequest>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Logs user into the system
 */

export function useLoginUser<TData = Awaited<ReturnType<typeof loginUser>>, TError = ErrorType<void>>(
 params: LoginUserParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof loginUser>>, TError, TData>>, request?: SecondParameter<typeof customRequest>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getLoginUserQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Logs out current logged in user session
 */
export type logoutUserResponseDefault = {
  data: void
  status: number
}
    
;
export type logoutUserResponseError = (logoutUserResponseDefault) & {
  headers: Headers;
};

export type logoutUserResponse = (logoutUserResponseError)

export const getLogoutUserUrl = () => {


  

  return `https://petstore.swagger.io/v2/user/logout`
}

export const logoutUser = async ( options?: RequestInit): Promise<logoutUserResponse> => {
  
  return customRequest<logoutUserResponse>(getLogoutUserUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getLogoutUserQueryKey = () => {
    return [
    `https://petstore.swagger.io/v2/user/logout`
    ] as const;
    }

    
export const getLogoutUserQueryOptions = <TData = Awaited<ReturnType<typeof logoutUser>>, TError = ErrorType<void>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof logoutUser>>, TError, TData>>, request?: SecondParameter<typeof customRequest>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLogoutUserQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof logoutUser>>> = ({ signal }) => logoutUser({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof logoutUser>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type LogoutUserQueryResult = NonNullable<Awaited<ReturnType<typeof logoutUser>>>
export type LogoutUserQueryError = ErrorType<void>


export function useLogoutUser<TData = Awaited<ReturnType<typeof logoutUser>>, TError = ErrorType<void>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof logoutUser>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof logoutUser>>,
          TError,
          Awaited<ReturnType<typeof logoutUser>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customRequest>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLogoutUser<TData = Awaited<ReturnType<typeof logoutUser>>, TError = ErrorType<void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof logoutUser>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof logoutUser>>,
          TError,
          Awaited<ReturnType<typeof logoutUser>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customRequest>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLogoutUser<TData = Awaited<ReturnType<typeof logoutUser>>, TError = ErrorType<void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof logoutUser>>, TError, TData>>, request?: SecondParameter<typeof customRequest>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Logs out current logged in user session
 */

export function useLogoutUser<TData = Awaited<ReturnType<typeof logoutUser>>, TError = ErrorType<void>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof logoutUser>>, TError, TData>>, request?: SecondParameter<typeof customRequest>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getLogoutUserQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




