import { defineCommand } from 'citty';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import chalk from 'chalk';
import matter from 'gray-matter';
import glob from 'fast-glob';

type ConvertScope = 'workspace' | 'global' | 'both';

function resolveAgentsDirs(cwd: string, scope: ConvertScope): { label: string; dir: string }[] {
  const home = os.homedir();
  switch (scope) {
    case 'workspace':
      return [{ label: 'workspace', dir: path.join(cwd, '.agents') }];
    case 'global':
      return [{ label: 'global', dir: path.join(home, '.agents') }];
    case 'both':
      return [
        { label: 'workspace', dir: path.join(cwd, '.agents') },
        { label: 'global', dir: path.join(home, '.agents') },
      ];
  }
}

export default defineCommand({
  meta: {
    name: 'convert',
    description: 'Convert IDE-specific configs into .agents/ format',
  },
  args: {
    from: {
      type: 'string',
      default: 'cursor',
      description: 'Source IDE to convert from (cursor)',
    },
    scope: {
      type: 'string',
      default: 'workspace',
      description: 'Where to save: workspace (.agents/) | global (~/.agents/) | both',
    },
    dryRun: {
      type: 'boolean',
      default: false,
      description: 'Preview changes without writing',
    },
  },
  async run({ args }) {
    const cwd = process.cwd();
    const from = String(args.from);
    const scope = String(args.scope) as ConvertScope;
    const dryRun = Boolean(args.dryRun);

    if (!['workspace', 'global', 'both'].includes(scope)) {
      console.error(chalk.red(`\n  ✗ Invalid scope: "${scope}". Use: workspace | global | both\n`));
      process.exit(1);
    }

    console.log(chalk.bold('\n🔀 agent-cli convert\n'));
    console.log(`  From:     ${chalk.yellow(from)}`);
    console.log(`  Scope:    ${chalk.cyan(scope)}`);
    console.log(`  Dry run:  ${dryRun ? chalk.green('yes') : chalk.dim('no')}\n`);

    if (from === 'cursor') {
      await convertFromCursor(cwd, scope, dryRun);
    } else {
      console.error(chalk.red(`  ✗ Unknown source: "${from}". Available: cursor\n`));
      process.exit(1);
    }
  },
});

async function convertFromCursor(cwd: string, scope: ConvertScope, dryRun: boolean) {
  const rulesDir = path.join(cwd, '.cursor', 'rules');

  try {
    await fs.access(rulesDir);
  } catch {
    console.log(chalk.yellow('  ⚠ No .cursor/rules/ directory found.\n'));
    return;
  }

  // Find all .mdc files (including subfolders)
  const mdcFiles = await glob('**/*.mdc', { cwd: rulesDir });

  if (mdcFiles.length === 0) {
    console.log(chalk.yellow('  ⚠ No .mdc files found in .cursor/rules/\n'));
    return;
  }

  // Skip auto-generated files
  const autoGenerated = ['_project-context.mdc', '_project-agents.mdc'];
  const userFiles = mdcFiles.filter((f) => !autoGenerated.includes(path.basename(f)));

  console.log(chalk.dim(`  Found ${mdcFiles.length} .mdc file(s), ${userFiles.length} to convert\n`));

  const destinations = resolveAgentsDirs(cwd, scope);

  for (const dest of destinations) {
    console.log(chalk.bold(`  ▸ ${dest.label}`) + chalk.dim(` (${dest.dir})\n`));

    let created = 0;
    let skipped = 0;

    for (const relPath of userFiles) {
      const absPath = path.join(rulesDir, relPath);
      const raw = await fs.readFile(absPath, 'utf-8');
      const { data, content } = matter(raw);

      const skillName = path.basename(relPath, '.mdc');
      const description = data.description ?? '';
      const skillContent = content.trim();

      if (!skillContent) {
        console.log(chalk.dim(`    ─ ${relPath} (empty, skipped)`));
        skipped++;
        continue;
      }

      const skillMd = [
        '---',
        `name: ${skillName}`,
        `description: ${description}`,
        '---',
        '',
        skillContent,
        '',
      ].join('\n');

      const targetPath = path.join(dest.dir, 'skills', skillName, 'SKILL.md');
      const targetRel = path.relative(cwd, targetPath);
      const displayPath = dest.label === 'global' ? `~/.agents/skills/${skillName}/SKILL.md` : targetRel;

      // Check if already exists
      try {
        await fs.access(targetPath);
        console.log(chalk.dim(`    ─ ${displayPath} (exists)`));
        skipped++;
        continue;
      } catch {
        // Doesn't exist
      }

      if (dryRun) {
        console.log(chalk.green(`    ✚ ${displayPath}`) + chalk.dim(` ← ${relPath}`));
      } else {
        await fs.mkdir(path.dirname(targetPath), { recursive: true });
        await fs.writeFile(targetPath, skillMd);
        console.log(chalk.green(`    ✚ ${displayPath}`) + chalk.dim(` ← ${relPath}`));
      }
      created++;
    }

    // Also check for .cursorrules legacy file
    const legacyPath = path.join(cwd, '.cursorrules');
    try {
      const legacyContent = await fs.readFile(legacyPath, 'utf-8');
      if (legacyContent.trim()) {
        const agentsMdPath = path.join(dest.dir, 'AGENTS.md');
        const displayPath = dest.label === 'global' ? '~/.agents/AGENTS.md' : path.relative(cwd, agentsMdPath);
        try {
          await fs.access(agentsMdPath);
          console.log(chalk.dim(`    ─ ${displayPath} (exists)`));
          skipped++;
        } catch {
          if (dryRun) {
            console.log(chalk.green(`    ✚ ${displayPath}`) + chalk.dim(` ← .cursorrules`));
          } else {
            await fs.mkdir(path.dirname(agentsMdPath), { recursive: true });
            await fs.writeFile(agentsMdPath, legacyContent);
            console.log(chalk.green(`    ✚ ${displayPath}`) + chalk.dim(` ← .cursorrules`));
          }
          created++;
        }
      }
    } catch {
      // No .cursorrules file
    }

    console.log(
      chalk.dim(`    ${created} created, ${skipped} skipped\n`)
    );
  }
}
